name: build

on:
  pull_request:
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: pip install \
             mkdocs-material \
             mkdocs-macros-plugin \
             mkdocs-glightbox

      - run: mkdocs build --strict